import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  buttonSkip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 30,
    marginTop: 10,
  },
  textSkip: {
    color: Colors.textGrayColor,
  },
  otpInputViewActive: {
    borderColor: Colors.buttonTextColor,
    backgroundColor: 'white',
    // minWidth: '13%',
    borderWidth: 1,
    borderRadius: 45,
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    padding: 8,
    elevation: 3,
    // marginLeft: 10,
    width: 45,
    height: 45,
  },
  otpInputText: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    fontFamily: 'SVN-Poppins-Medium',
    fontWeight: '500',
  },
  otpInputView: {
    // borderColor: Colors.buttonTextColor,
    // minWidth: '13%',
    // borderWidth: 1,
    backgroundColor: 'white',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderRadius: 45,
    elevation: 3,
    padding: 8,
    // marginLeft: 10,
    width: 45,
    height: 45,
  },
  inputContainerPressable: {
    width: widthDevice - 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputSection: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  hiddenTextInput: {
    // borderColor: '#004D40',
    // borderWidth: 2,
    // borderRadius: 5,
    // padding: 12,
    // marginTop: 15,
    // width: 300,
    // color: 'white',
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  wrapperInput: {
    // height: heightDevice / 3,
    // backgroundColor: 'red',
    marginBottom: 10,
  },
  textError: {
    color: Colors.redColor,
    marginHorizontal: 15,
    textAlign: 'center',
    marginTop: 20,
  },
  textReceive: {
    textAlign: 'center',
    fontSize: 16,
    color: Colors.textGrayColor,
    fontFamily: 'SVN-Poppins-Medium',
    marginTop: 10,
  },
  textSend: {
    textAlign: 'center',
    fontSize: 16,
    textDecorationLine: 'underline',
    color: Colors.buttonTextColor,
    fontFamily: 'SVN-Poppins-Medium',
  },
  textSendMessage: {
    textAlign: 'center',
    fontSize: 16,
    color: Colors.buttonTextColor,
    fontFamily: 'SVN-Poppins-Medium',
  },
  viewButton: {
    // justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0.09 * heightDevice,
    // backgroundColor: 'red',
    marginBottom: 0.22 * heightDevice,
  },
  buttonConfirm: {
    width: widthDevice / 1.5,
    paddingVertical: 12,
    borderRadius: 30,
    backgroundColor: '#004D40',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textButton: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 20,
  },
  wrapperTitle: {
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'red',
  },
  imageStyle: {
    width: 80,
    height: 85,
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: '500',
    lineHeight: 27,
    letterSpacing: 0,
    color: 'black',
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'SVN-Poppins-Medium',
  },
  subtitle: {
    textAlign: 'center',
    fontSize: 15,
    marginBottom: 20,
    color: Colors.textGrayColor,
    fontFamily: 'SVN-Poppins-Medium',
  },
  separatorLine: {
    width: '70%',
    color: '#004D40',
    marginVertical: 0.04 * heightDevice,
  },
  dot: {
    backgroundColor: '#004D40',
    width: 70,
    height: 30,
    position: 'absolute',
    right: widthDevice / 3.2,
    top: heightDevice / 13,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconStar: {
    color: 'white',
  },
  indicator: {
    position: 'absolute',
    top: heightDevice / 2 - 20,
    left: widthDevice / 2 - 20,
  },
});

export default styles;
