export default {
  login: 'Login',
  common: {
    continue: 'Continue',
    store: 'Stores',
    home: 'Home',
    reviews: 'Reviews',
    user: 'User',
    notification: 'Notification',
    categories: 'Categories',
    deliveryAddress: 'Delivery Address',
    errorOccurred: 'An error occurred, please try again!',
    findDeliveryAddress: 'Find the delivery address',
    orderSuccess: 'Order successfully',
    orderFailure: 'Order failed, please try again!',
    rateOrderQuestion: 'Do you want to rate the order',
    updateNotification:
      'The Neo Cafe app has a newly updated version. Would you like to use the new version immediately?',
    finish: 'Finish',
    suitableCafe: 'Suitable Neo Cafe locations for you',
    address: 'Address',
    shippingAddress: 'Shipping Address',
    loginNotification: 'You need to log in to experience features on the app',
    confirm: 'Confirm',
    evoucherNotEnough:
      'Your E-Voucher 1 balance is not enough to subscribe to the package. Please refill to continue service.',
    select: 'Select',
    notValidPhoneReferal: 'The referrer`s phone number is invalid.',
    enterReferalPhone: 'Enter the referrer`s phone number',
    confirmSubcription: 'Confirm Subcription',
    selected: 'Selected',
    distance: 'Distance',
    suitablePackage: 'Suitable subscription package for you',
    serviceNotAvailable: '	Service is not available',
    all: 'All',
    over2kmWarning:
      'Your address is outside the 2km radius, we will notify you when there is a new shop near you.',
    selectStore: 'Select Store',
    subscribe: 'Subscribe',
    login: 'Login',
    back: 'Back',
    send: 'Send',
    selectPackageWarning: 'Please select a package to continue registration.',
    logout: 'Logout',
    available: 'Available',
    expiredDate: 'Expired Date',
    yes: 'Yes',
    claimed: 'Claimed',
    no: 'No',
    expired: 'Expired',
    vietnamese: 'Vietnamese',
    english: 'English',
    order: 'Order',
    month: 'month',
    day: 'day',
    minute: 'minutes',
    save: 'Save',
    description: 'Description',
    quantity: 'Quantity',
    canceled: 'Canceled',
    completed: 'Completed',
    confirmed: 'Confirmed',
    serving: 'Processing',
    skip: 'Skip',
    note: 'Note',
    pending: 'Pending',
    buynow: 'Buy Now',
    soldOut: 'Sold out',
    pleaseComeCounter:
      'Please come to the counter for advice and purchase from staff',
  },

  loginScreen: {
    greeting: 'Hi,',
    continue: 'Continue',
    title: 'Please enter your phone number to log in',
    checkboxPolicy: 'I agree with the terms and conditions',
    policyInfo: 'Privacy Policy',
    hotline: 'Contact hotline',
    notValidPhone: 'Please enter a correct phone number',
  },
  verifyScreen: {
    confirmOtp: 'Verify OTP Code',
    title: 'Enter the OTP code sent to',
    question: 'Have you received the OTP code yet?',
    resendRespond: 'Confirmation code sent again. Please check!',
    verifyContinue: 'Verify & Continue',
    sendBack: 'Resend',
    errorMessageOtp: 'Expired credentials or Invaid code',
    errorMessageApp:
      'An error occurred during the verification process. Please contact the service personnel',
  },
  locationScreen: {
    question: 'Allow Neo Cafe to use your location?',
    subtitle: 'Allow Neo Cafe to know your location to find the nearest store.',
    turnonGPS: 'Turn on GPS',
  },
  homeScreen: {
    featuredProducts: 'Featured products',
    greeting: 'Hi',
    searchInput: 'Search for your favorites',
    emptyNotifications: 'No new notifications',
  },
  shopScreen: {
    placeholderInput: 'Find the nearest store',
    removeOrderBeforeChange:
      'Products in the cart will be cleared when you change the store address',
    detectingNotification: 'Your nearest store has changed. Please confirm!',
    detectingNotification1: 'Your location has changed to near the',
    detectingNotification2:
      'Do you want to update the menu on the application?',
  },
  reviewScreen: {
    atmosphere: 'Atmosphere',
    service: 'Service',
    addphoto: 'Add Photo',
    product: 'Product',
    placeholderInput:
      'Please share details of your own experience at this place',
  },
  accountScreen: {
    account: 'Account',
    balance: 'Balance',
    accountStatement: 'Account Statement',
    orderHistory: 'Order History',
    freeshipPackage: 'Freeship Package',
    depositHistory: 'Deposit History',
    available: 'Available',
    voucherTitle: 'Voucher',
    eVoucher1: 'Top up E-voucher points 1',
    eVoucher2: 'Bonus E-voucher points 2',
    listShop: 'List of Shop',
    language: 'Language',
    inputReferal: 'Input referral code',
    selectStore: 'Select store',
    giftCode: 'Gift Code',
    inputVoucher: 'Input voucher',
    applyVoucherSuccess: 'Apply voucher code successfully',
    applyVoucherFailed: 'Apply voucher code failed',
    applyReferralSuccess: 'Apply referral code successfully',
    applyReferralFailed: 'Apply referral code failed',
    inputPhone: 'Input your phone number',
    referralCode: 'Referral Code',
    registered: 'Registered',
    unregistered: 'Unregistered',
    unsubscribe: 'Unsubscribe',
    female: 'Female',
    male: 'Male',
    accountInformation: 'Account Information',
    other: 'Other',
    expired: 'Expired',
    notData: 'Not data',
    name: 'Name',
    claimed: 'Claimed',
    dateofBirth: 'Date of Birth',
    deleteAccount: 'Delete Account',
    selectGender: 'Please select gender',
    deleteNotification: 'Are you sure you want to delete this account?',
    updateNotiSuccess: 'Successfully updated',
    updateNotiError: 'Updating information failed',
    pleaseSelectBirthday: 'Please select date of birth',
    logout: 'Logout',
  },
  detailOrderScreen: {
    cancel: 'Cancel',
    reorder: 'Re-order',
    review: 'Review',
    orderDetails: 'Order Details',
    reorderWarning:
      '*If you choose to reorder, the cart will delete the items you previously selected.',
    orderedDrinks: 'Ordered Drinks',
    orderId: 'Order ID',
    totalAmount: 'Total Amount',
    orderTime: 'Order Time',
    reorderFailed:
      'is temporarily out of stock. Please choose another product. Best regards!',
    cancelOrderConfirm: 'Please confirm order cancellation',
    cancelOrderSuccess: 'Cancel order successfully',
    cancelOrderError: 'Order cancellation failed. Please try again later!',
    questionReorder: 'Do you want to continue reordering?',
  },
  cartScreen: {
    orderBtn: 'Order',
    getAtCounter: 'Order takeaway and pick up at the counter',
    consumeAtStore: 'Consume at the store',
    receiveMethod: 'Receiving Method',
    totalAmount: 'Total Amount',
    listProducts: 'Ordered Drinks',
    changeLocation: 'Change Location',
    inputTable: 'Input Table Number',
    deliveryAddress: 'Delivery Address',
    receiveCounterTime: '	Receive your order later at the counter: ',
    tableTimeWarning: 'Please select table number or pick up time.',
  },
  freeshipScreen: {
    packageName: 'Package Name: ',
    packageAddress: 'Package Address: ',
    packageTime: 'Time: ',
    radius: 'Radius: ',
    status: 'Status: ',
    inactive: 'Inactive',
    active: 'Active',
    packageRenewalCanceled: 'Package renewal canceled',
    cancelRenewal: 'Cancel Renewal',
    freeshipPackage: 'Freeship Package',
    listPackage: 'List of Package',
    myPackage: 'My Package',
    subscribe: 'Subscribe',
    cancelRenewalSuccess: 'Cancel renewal successfully',
    confirmCancel: 'Confirm cancellation of package renewal',
  },
};
