export default {
  login: 'Đăng nhập',
  common: {
    continue: 'Tiếp tục',
    store: 'Cửa hàng',
    home: 'Trang Chủ',
    select: 'Chọn',
    selected: 'Đã chọn',
    subscribe: 'Đăng kí',
    updateNotification:
      'App Neo Cafe có 1 phiên bản mới cập nhật. Bạn có muốn sử dụng ngay phiên bản mới không.',
    deliveryAddress: 'Địa chỉ nhận hàng',
    rateOrderQuestion: 'Bạn có muốn đánh giá đơn hàng',
    orderSuccess: 'Đặt hàng thành công',
    orderFailure: 'Đặt hàng thất bại. Vui lòng thử lại !',
    reviews: 'Đánh giá',
    suitablePackage: 'Gói phù hợp với bạn',
    errorOccurred: 'Có lỗi xảy ra vui lòng thử lại!',
    shippingAddress: 'Điểm giao hàng',
    confirmSubcription: 'Xác nhận đăng kí',
    distance: 'Khoảng cách',
    enterReferalPhone: 'Nhập số điện thoại người giới thiệu',
    evoucherNotEnough:
      'Số dư E-Voucher 1 của bạn không đủ để đăng ký gói. Vui lòng nạp thêm để tiếp tục dịch vụ.',
    over2kmWarning:
      'Địa chỉ của bạn nằm ngoài bán kính 2km, chúng tôi sẽ thông báo đến bạn khi có Quán mới gần bạn nhất.',
    suitableCafe: 'Quán Neo Cafe phù hợp với bạn',
    findDeliveryAddress: 'Tìm kiếm địa chỉ nhận hàng ...',
    categories: 'Danh mục',
    notValidPhoneReferal: ' Số điện thoại người giới thiệu không hợp lệ.',
    user: 'Tài khoản',
    notification: 'Thông báo',
    selectPackageWarning: 'Vui lòng chọn gói để tiếp tục đăng ký',
    address: 'Địa chỉ',
    login: 'Đăng nhập',
    serviceNotAvailable: 'Dịch vụ không khả dụng',
    all: 'Tất cả',
    logout: 'Đăng xuất',
    note: 'Ghi chú',
    finish: 'Hoàn Thành',
    loginNotification:
      'Bạn cần phải đăng nhập để trải nghiệm tính năng trên app',
    confirm: 'Xác nhận',
    english: 'English',
    vietnamese: 'Tiếng Việt',
    back: 'Trở về',
    description: 'Mô tả',
    quantity: '	Số lượng ',
    send: 'Gửi',
    month: 'tháng',
    day: 'ngày',
    order: 'Đơn hàng',
    skip: 'Bỏ qua',
    minute: 'phút',
    yes: 'Có',
    no: 'Không',
    expiredDate: 'Hạn sử dụng',
    canceled: '	Đã hủy',
    claimed: 'Đã sử dụng',
    expired: 'Hết hạn',
    available: 'Khả dụng',
    completed: 'Đã hoàn thành',
    serving: 'Đang giao hàng',
    confirmed: 'Đã xác nhận',
    pending: 'Đang chờ',
    save: 'Lưu',
    buynow: 'Mua Ngay',
    soldOut: 'Tạm hết hàng',
    pleaseComeCounter:
      'Quý khách vui lòng tới quầy để được nhân viên tư vấn và mua hàng',
  },
  loginScreen: {
    greeting: 'Xin chào,',
    continue: 'Tiếp tục',
    title: 'Vui lòng nhập số điện thoại để đăng nhập',
    checkboxPolicy: 'Tôi đồng ý với điều khoản và chính sách',
    policyInfo: 'Chinh sách bảo mật',
    notValidPhone: 'Xin vui lòng nhập đúng số điện thoại',
    hotline: '	Liên hệ hotline',
  },
  verifyScreen: {
    confirmOtp: 'Xác nhận mã OTP',
    title: 'Nhập mã OTP đã gửi đến',
    question: 'Bạn không nhận được mã OTP ?',
    resendRespond: 'Đã gửi lại mã xác nhận. Vui lòng kiểm tra!',
    verifyContinue: 'Xác nhận & tiếp tục',
    sendBack: 'Gửi lại mã',
    errorMessageOtp:
      'Mã xác thực đã hết hạn hoặc không đúng. Vui lòng thử lại!',
    errorMessageApp:
      'Xảy ra lỗi trong quá trình xác thực. Vui lòng liên hệ nhân viên phục vụ',
  },
  locationScreen: {
    question: 'Cho phép “Neo Cafe” sử dụng vị trí của bạn?',
    subtitle:
      'Cho phép “Neo Cafe” được biết vị trí của bạn để tìm của hàng gần nhất.',
    turnonGPS: 'Bật GPS',
  },
  homeScreen: {
    greeting: 'Xin chào',
    featuredProducts: 'Sản phẩm nổi bật',
    searchInput: 'Tìm đồ uống yêu thích',
    emptyNotifications: 'Không có thông báo mới',
  },
  shopScreen: {
    placeholderInput: 'Tìm cửa hàng',
    removeOrderBeforeChange:
      'Sản phẩm trong giỏ hàng sẽ bị xóa hết khi thay đổi địa chỉ cửa hàng',
    detectingNotification:
      'Cửa hàng gần nhất của bạn đã thay đổi.Vui lòng xác nhận!',
    detectingNotification1: 'Vị trí của bạn đã thay đổi đến gần cửa hàng',
    detectingNotification2: 'bạn muốn cập nhật lại menu trên ứng dụng không?',
  },
  reviewScreen: {
    atmosphere: 'Không gian',
    service: 'Phục vụ',
    product: 'Sản phẩm',
    placeholderInput: 'Hãy chia sẻ cảm nhận của bạn với chúng tôi',
    addphoto: 'Thêm hình ảnh',
  },
  accountScreen: {
    account: 'Tài khoản',
    listShop: 'Danh sách quán',
    balance: 'Số dư',
    language: 'Ngôn ngữ',
    eVoucher1: 'Nạp điểm E-voucher 1',
    eVoucher2: 'Tặng điểm E-voucher  2',
    accountStatement: 'Sao kê tài khoản',
    depositHistory: 'Lịch sử  nạp điểm',
    orderHistory: 'Lịch sử đơn hàng',
    freeshipPackage: 'Gói Free Ship',
    voucherTitle: 'Quà tặng',
    giftCode: 'Mã quà tặng',
    notData: 'Không có dữ liệu',
    applyVoucherSuccess: 'Áp dụng mã voucher thành công',
    applyVoucherFailed: 'Mã voucher không khả dụng',
    applyReferralSuccess: 'Áp dụng mã giới thiệu thành công',
    applyReferralFailed: 'Mã giới thiệu không khả dụng',
    referralCode: 'Mã giới thiệu',
    registered: 'Đã đăng ký',
    unregistered: 'Chưa đăng ký',
    unsubscribe: 'Hủy đăng kí',
    female: 'Nữ',
    male: 'Nam',
    inputVoucher: 'Nhập mã voucher',
    inputPhone: 'Vui lòng nhập số điện thoại',
    inputReferal: 'Nhập mã giới thiệu',
    claimed: 'Đã sử dụng',
    expired: 'Hết hạn',
    available: 'Khả dụng',
    other: 'Khác',
    name: 'Họ và Tên',
    dateofBirth: 'Ngày tháng năm sinh',
    deleteAccount: 'Xóa tài khoản',
    accountInformation: 'Thông tin tài khoản',
    deleteNotification: 'Bạn có chắc chắn muốn xóa tải khoản này',
    selectGender: 'Vui lòng lựa chọn giới tính',
    updateNotiSuccess: 'Cập nhật thông tin thành công',
    updateNotiError: 'Cập nhật thông tin thất bại',
    pleaseSelectBirthday: 'Vui lòng chọn ngày tháng năm sinh',
    logout: 'Đăng xuất',
  },
  detailOrderScreen: {
    cancel: 'Hủy đơn',
    reorder: 'Đặt lại',
    selectStore: 'Lựa chọn cửa hàng',
    orderDetails: 'Chi tiết đơn hàng',
    review: 'Đánh giá',
    reorderWarning:
      '*Nếu chọn đặt lại thì giỏ hàng sẽ xóa các món mà bạn đã chọn trước đó',
    orderedDrinks: 'Món đã đặt',
    orderId: 'Mã đơn',
    totalAmount: 'Tổng tiền',
    orderTime: 'Thời gian đặt hàng',
    reorderFailed: 'không có trong Menu của cửa hàng',
    cancelOrderConfirm: 'Vui lòng xác nhận hủy đơn hàng',
    cancelOrderSuccess: 'Hủy đơn hàng thành công!',
    cancelOrderError: 'Hủy đơn hàng thất bại. Vui lòng thử lại sau!',
    questionReorder: 'Bạn có muốn tiếp tục đặt lại không?',
  },
  cartScreen: {
    orderBtn: 'Đặt hàng',
    getAtCounter: 'Đặt mang đi và nhận món tại quầy',
    consumeAtStore: 'Trải nghiệm tại cửa hàng',
    receiveMethod: 'Phương thức nhận hàng',
    totalAmount: 'Tổng tiền',
    listProducts: 'Món đã đặt',
    changeLocation: 'Thay đổi địa điểm',
    inputTable: 'Nhập số bàn',
    deliveryAddress: 'Địa chỉ nhận',
    receiveCounterTime: 'Nhận món tại quầy sau: ',
    tableTimeWarning: 'Vui lòng chọn số bàn hoặc thời gian nhận.',
  },
  freeshipScreen: {
    packageName: 'Tên gói: ',
    packageAddress: 'Địa chỉ nhận: ',
    packageTime: 'Thời gian: ',
    radius: 'Bán kính: ',
    status: 'Trạng thái: ',
    inactive: 'Chưa kích hoạt',
    active: 'Đã kích hoạt',
    packageRenewalCanceled: 'Đã hủy gia hạn gói',
    cancelRenewal: 'Hủy gia hạn',
    freeshipPackage: 'Gói Free Ship',
    listPackage: 'Danh sách gói',
    myPackage: 'Gói của tôi',
    subscribe: 'Đăng ký',
    cancelRenewalSuccess: 'Hủy gia hạn thành công',
    confirmCancel: 'Xác nhận hủy gia hạn gói',
  },
};
